In [2]:
import pandas as pd

X = pd.read_csv('../data/secom.data', sep=' ', header=None)
y = pd.read_csv('../data/secom_labels.data', sep=' ', header=None,
names=['label', 'time'])

y['time'] = pd.to_datetime(y['time'].str.strip('"'), format='%d/%m/%Y %H:%M:%S')

In [33]:
X.head()

,0,1,2,3,4,5,6,7,8,9,...,580,581,582,583,584,585,586,587,588,589
0,3030.93,2564.00,2187.7333,1411.1265,1.3602,100.0,97.6133,0.1242,1.5005,0.0162,...,NaN,NaN,0.5005,0.0118,0.0035,2.3630,NaN,NaN,NaN,NaN
1,3095.78,2465.14,2230.4222,1463.6606,0.8294,100.0,102.3433,0.1247,1.4966,-0.0005,...,0.0060,208.2045,0.5019,0.0223,0.0055,4.4447,0.0096,0.0201,0.0060,208.2045
2,2932.61,2559.94,2186.4111,1698.0172,1.5102,100.0,95.4878,0.1241,1.4436,0.0041,...,0.0148,82.8602,0.4958,0.0157,0.0039,3.1745,0.0584,0.0484,0.0148,82.8602
3,2988.72,2479.90,2199.0333,909.7926,1.3204,100.0,104.2367,0.1217,1.4882,-0.0124,...,0.0044,73.8432,0.4990,0.0103,0.0025,2.0544,0.0202,0.0149,0.0044,73.8432
4,3032.24,2502.87,2233.3667,1326.5200,1.5334,100.0,100.3967,0.1235,1.5031,-0.0031,...,NaN,NaN,0.4800,0.4766,0.1045,99.3032,0.0202,0.0149,0.0044,73.8432

In [34]:
y.head()

   label                time
0     -1 2008-07-19 11:55:00
1     -1 2008-07-19 12:32:00
2      1 2008-07-19 13:17:00
3     -1 2008-07-19 14:43:00
4     -1 2008-07-19 15:22:00

In [36]:
X.shape

(1567, 590)

In [37]:
y.shape

(1567, 2)

In [40]:
y['label'].value_counts()

label
-1    1463
 1     104
Name: count, dtype: int64

In [41]:
y['label'].value_counts(normalize=True)

label
-1    0.933631
 1    0.066369
Name: proportion, dtype: float64

In [47]:
(X.isna().mean() > 0.5).sum()

np.int64(28)

In [45]:
(X.nunique() == 1).sum()

np.int64(116)

In [46]:
X.isna().mean().sort_values(ascending=False).head(3)

292    0.911934
293    0.911934
158    0.911934
dtype: float64

In [50]:
cols = [292, 293, 158]
X[cols].isna().all(axis=1).sum()

np.int64(1429)

In [51]:
mr = X.isna().mean()

In [52]:
(mr == mr.max()).sum()

np.int64(4)

In [53]:
y['time'].is_monotonic_increasing

True

In [72]:
n = int(len(X) * 0.8)

In [79]:
X_train, X_test = X.iloc[:n], X.iloc[n:]
y_train, y_test = y.iloc[:n], y.iloc[n:]

print(y_train['label'].value_counts())
print(y_train['label'].value_counts(normalize=True))

label
-1    1166
 1      87
Name: count, dtype: int64
label
-1    0.930567
 1    0.069433
Name: proportion, dtype: float64

In [80]:
print(y_test['label'].value_counts())
print(y_test['label'].value_counts(normalize=True))

label
-1    297
 1     17
Name: count, dtype: int64
label
-1    0.94586
 1    0.05414
Name: proportion, dtype: float64

In [84]:
print(y['time'].min())
print(y['time'].max())

2008-07-19 11:55:00
2008-10-17 06:07:00

In [85]:
X_train.nunique() == 1

0      False
1      False
2      False
3      False
4      False
       ...
585    False
586    False
587    False
588    False
589    False
Length: 590, dtype: bool

In [88]:
# 값이 1종류뿐인 칼럼
const_cols = X_train.columns[X_train.nunique() == 1]

# 결측률 50% 초과 컬럼
missing_cols = X_train.columns[X_train.isna().mean() > 0.5]

print(len(const_cols), len(missing_cols))

drop_cols = set(const_cols) | set(missing_cols)
print(len(drop_cols))

X_train2 = X_train.drop(columns=drop_cols)
X_test2 = X_test.drop(columns=drop_cols)

median = X_train2.median()
X_train2 = X_train2.fillna(median)
X_test2 = X_test2.fillna(median)

print(X_train2.shape, X_test2.shape)
print(X_train2.isna().sum().sum(), X_test2.isna().sum().sum())

122 24
146

(1253, 444) (314, 444)
0 0